sudo: false
dist: trusty

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
    yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Node 10"
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test:node
    - name: "Node 8"
      script:
        - yarn test:node
    - name: "Node 6"
      script:
        - yarn test:node
    - name: "Floating Dependencies"
      install:
        - yarn install --no-lockfile --non-interactive
      script:
        - yarn test:node

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --frozen-lockfile --non-interactive

script:
  - yarn ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
  - yarn test:node # uses the current scenario's ember-source

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: Y5uNST9XrrvGreK+UhNob9ZgjPcwfRoOFpkBpeEMBk5V5fGy9RsAA4RE6VHQtnqPnhpYORXZDe7UK8AgiVXB3pgzxJ1E5N68dbphWjWhZMefbsXbTikHERkYauHlTXuJ6tOMabD9tdxhe4Dsvox/wayP2svOqtpXtkjzvIHhO1c=
  on:
    tags: true
    repo: ember-cli/ember-cli-htmlbars
