name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request: {}
  schedule:
  - cron:  '0 6 * * 0' # weekly, on sundays

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: yarn install
    - name: lint:js
      run: yarn lint:js
    - name: lint:hbs
      run: yarn lint:hbs

  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: yarn install
    - name: node tests
      run: yarn test:node
    - name: ember test
      run: yarn test:ember

  floating-dependencies:
    name: Floating Deps
    runs-on: ubuntu-latest

    needs: [test, lint]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: yarn install --ignore-lockfile
    - name: node tests
      run: yarn test:node
    - name: ember test
      run: yarn test:ember

  try-scenarios:
    name: ${{ matrix.ember-try-scenario }}

    runs-on: ubuntu-latest

    needs: [test, lint]

    strategy:
      matrix:
        ember-try-scenario:
         - ember-lts-2.12
         - ember-lts-2.16
         - ember-lts-2.18
         - ember-lts-3.4
         - ember-lts-3.8
         - ember-lts-3.12
         - ember-release
         - ember-octane
         - ember-beta
         - ember-canary
         - ember-default
         - ember-default-with-jquery
         - with-ember-cli-htmlbars-inline-precompile

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: yarn install
    - name: test
      env:
        EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
      run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
